version: "4"

services:
  postgres:
    image: postgres:17
    container_name: db
    hostname: db
    environment:
      POSTGRES_USER: administrator
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
